---
include:
  - project: 'gportal/docker/base-images'
    ref: main
    file: '/templates/.gitlab-ci-template.yml'

stages:
  - build

build:
  stage: build
  image: golang:1.21
  script:
    - go generate
    - go build -o ./gpc ./gpc.go
