---
include:
  - project: 'gportal/docker/base-images'
    ref: main
    file: '/templates/.gitlab-ci-template.yml'

stages:
  - build

build:
  stage: build
  image: golang:1.21
  artifacts:
    expire_in: 1 hour
    paths:
      - gpc
  script:
    - go generate
    - go build --ldflags="-s -w -X gpcloud-cli/cmd.GitCommit=$(git rev-parse HEAD)" -o ./gpc ./gpc.go
