// Code generated DO NOT EDIT
// This code is AUTOGENERATED and will be overwritten by "go generate", so
// editing this file is a waste of time. To make changes, edit the template
// in pkg/generator/template/rootcommand.tmpl. If you want to execute things
// before or after the command is executed, use a hook. See the usage_hook.go
// as an example.

package datacenter

import (
	"github.com/spf13/cobra"
)

var RootDatacenterCommand = &cobra.Command{
	Use:                   "datacenter",
	Short:                 "",
	Long:                  "",
	DisableFlagsInUseLine: true,
	Args:                  cobra.MatchAll(cobra.ExactArgs(0), cobra.OnlyValidArgs),
	RunE: func(cmd *cobra.Command, args []string) error {
		return cmd.Usage()
	},
}
