// Code generated DO NOT EDIT
// This code is AUTOGENERATED and will be overwritten by "go generate", so
// editing this file is a waste of time. To make changes, edit the template
// in pkg/generator/template/subcommand.tmpl. If you want to execute things
// before or after the command is executed, use a hook. See the usage_hook.go
// as an example.

package project

import (
	cloudv1 "buf.build/gen/go/gportal/gportal-cloud/protocolbuffers/go/gpcloud/api/cloud/v1"
	"encoding/json"
	"github.com/G-PORTAL/gpcloud-go/pkg/gpcloud/client"
	"github.com/spf13/cobra"
	"gpcloud-cli/pkg/config"
)

var imagesCmd = &cobra.Command{
	Use:                   "images",
	Short:                 "",
	Long:                  "",
	DisableFlagsInUseLine: true,
	Args:                  cobra.OnlyValidArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		conn := cmd.Context().Value("conn").(*client.Client)
		session := cmd.Context().Value("session").(*config.SessionConfig)
		resp, err := conn.CloudClient().ListProjectImages(cmd.Context(), &cloudv1.ListProjectImagesRequest{
			Id: *session.CurrentProject,
		})
		if err != nil {
			return err
		}

		// TODO: Call hook if exist

		// TODO: Only Output response as json if requests with --json flag,
		// Otherwise, output a human readable table
		jsonData, err := json.MarshalIndent(resp, "", "  ")
		if err != nil {
			return err
		}
		cmd.Println(string(jsonData))

		return nil
	},
}

func init() {

	RootProjectCommand.AddCommand(imagesCmd)
}
