// Code generated DO NOT EDIT
// This code is AUTOGENERATED and will be overwritten by "go generate", so
// editing this file is a waste of time.

package cmd

import (
	"github.com/spf13/cobra"
	"gpcloud-cli/cmd/county"
	"gpcloud-cli/cmd/datacenter"
	"gpcloud-cli/cmd/node"
	"gpcloud-cli/cmd/project"
	"gpcloud-cli/cmd/user"
)

func AddGeneratedCommands(cmd *cobra.Command) {
	cmd.AddCommand(county.RootCountyCommand)
	cmd.AddCommand(datacenter.RootDatacenterCommand)
	cmd.AddCommand(node.RootNodeCommand)
	cmd.AddCommand(project.RootProjectCommand)
	cmd.AddCommand(user.RootUserCommand)

}
