package generator

import (
	. "github.com/dave/jennifer/jen"
	"strings"
)

// warningComment adds a warning comment to the file. This will be added to all
// generated files to warn the developer that the file is autogenerated and
// should not be edited.
func warningComment(f *File) {
	f.Comment("Code generated DO NOT EDIT")
	f.Comment("This code is AUTOGENERATED and will be overwritten by \"go generate\", so")
	f.Comment("editing this file is a waste of time. To make changes, edit the template")
	f.Comment("in pkg/generator/template/subcommand.tmpl. If you want to execute things")
	f.Comment("before or after the command is executed, use a hook. See the usage_hook.go")
	f.Comment("as an example.")
	f.Line()
}

// escapePackage replaces dots and dashes with underscores. This is needed to
// set valid variable names (without dots and dashes).
func escapePackage(name string) string {
	return strings.Replace(strings.Replace(name, ".", "_", -1), "-", "_", -1)
}
