description: Project related actions

actions:
  list:
    api-call: cloud.ListProjects
    description: List all projects
    identifier: nil
    root-key: Projects
    fields:
      - Id
      - Name
      - Description
      - Currency.Currency

  get:
    api-call: cloud.GetProject
    description: Get details for a project
    identifier: nil
    params:
      - name: id
        type: string
        description: Project ID
        required: true

  # TODO: Fix after dependency upgrade
  update:
    api-call: cloud.UpdateProject
    description: Update project details
    params:
      - name: name
        type: string
        description: Project name
        required: true
      - name: description
        type: string
        description: Project description
        required: true
      - name: environment
        type: cloudv1.ProjectEnvironment
        description: Project environment
        default: cloudv1.PROJECT_ENVIRONMENT_DEVELOPMENT
        required: true
      - name: credit_card_id
        type: string
        description: Credit card ID
        required: true
      - name: billing_address_id
        type: string
        description: Billing address ID
        required: true

  create:
    api-call: cloud.CreateProject
    description: Create a new project
    identifier: nil
    params:
      - name: name
        type: string
        description: Project name
        required: true
      - name: description
        type: string
        default: ""
      - name: environment
        type: cloudv1.ProjectEnvironment
        default: cloudv1.PROJECT_ENVIRONMENT_DEVELOPMENT
        required: true
      - name: billing_address_id
        type: string
        required: true

  delete:
    api-call: cloud.DeleteProject
    description: Delete a project
    identifier: nil
    params:
      - name: id
        type: string
        description: Project ID to delete
        required: true

  flavours:
    api-call: cloud.ListProjectFlavours
    description: List all flavours in the project
    params:
      - name: datacenter_id
        description: Datacenter to fetch the flavours from
        type: string
        required: true
    fields:
      - Id
      - Name
      - Availability.FlavourAvailability
      - PricePerMonth.Price
      - PricePerHour.Price

  networks:
    api-call: admin.ListProjectNetworks
    description: List all networks in the project

  # network-create is implemented in code, because it is a special case
  # where we need to create a network and then attach it to the project.
  # Also, the datacenter is a struct, which is not possible to pass as a
  # parameter.

  logs:
    api-call: cloudv2.ListProjectLogs
    description: List all logs in the project
    fields:
      - CreatedAt.DateTime
      - User.BasicUser
      - Message

  # Join/Leave project
  join:
    api-call: cloud.JoinProject
    description: Join a project
    params:
      - name: accept
        type: bool
        default: false

  leave:
    api-call: cloud.LeaveProject
    description: Leave a project

  invite-member:
    api-call: cloud.InviteMemberToProject
    description: Invite a member to the project
    identifier: nil
    params:
      - name: id
        description: Project ID
        type: string
        required: true
      - name: identifier
        ##description: ??
        type: string
        required: true

  remove-member:
    api-call: cloud.RemoveMemberFromProject
    description: Remove a member from the project
    params:
      - name: user_id
        type: string
        required: true

  default-project:
    api-call: cloud.ChangeDefaultProject
    description: Change the default project
    identifier: nil
    params:
      - name: id
        type: string
        description: New default project ID
        required: true

  # Project information
  locks:
    api-call: cloud.GetProjectLocks
    description: List all locks in the project

  usage:
    api-call: cloud.GetProjectUsage
    description: Get project usage
    params:
      - name: detailed
        type: bool
        default: false

  images:
    api-call: cloud.ListProjectImages
    description: List all images in the project

  # TODO: Custom formatter to output keys in authorized_keys format
  ssh-keys:
    api-call: cloud.ListProjectSSHKeys
    description: List all SSH keys in the project
    root-key: Keys
    fields:
      - User.BasicUser
      - SshKey.SshKey


identifier: session.CurrentProject
