actions:
  list:
    api-call: cloud.ListProjects
    identifier: nil
    root-key: Projects
    fields:
      - Id
      - Name
      - Description
      - Currency

  # Join/Leave project
  join:
    api-call: cloud.JoinProject
    params:
      accept: bool
  leave:
    api-call: cloud.LeaveProject

  default-project:
    api-call: cloud.ChangeDefaultProject
    identifier: nil
    params:
      id: string

  # Project information
  locks:
    api-call: cloud.GetProjectLocks
    description: List all locks in the project
  usage:
    api-call: cloud.GetProjectUsage
    params:
      detailed: bool
  images:
    api-call: cloud.ListProjectImages
  ssh-keys:
    api-call: cloud.ListProjectSSHKeys
    root-key: Keys

identifier: session.CurrentProject
