name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod download

      - name: Generate code
        run: go generate ./...

      - name: Run tests
        run: go test -v ./...
